name: kidney-graft-tcr-nc
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.5
  - r-seurat
  - bioconductor-limma
  - r-statmod
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-stringr
  - r-patchwork
  - r-cowplot
  - r-ggrepel
  - r-matrix
  - r-data.table
  - r-pheatmap
  - r-remotes
  - r-monocle3
  - bioconductor-edger
  - python
  - pymupdf
  - pandas
  - numpy
  - matplotlib
